# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyFirebaseApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyFirebaseApp
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  #pod 'FirebaseUI' #This one supports all
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'
  pod 'FirebaseUI/Database'
end
