# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShopifyMobile' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShopifyMobile
  pod "Mobile-Buy-SDK"


  target 'ShopifyMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShopifyMobileUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
